<div style="background:#fff;padding:10px;font-size:14px;font-family:Tahoma;"><img style="margin-right:8px;margin-left:8px;vertical-align: middle;border:none" src="/bravia/soccer.png" /><a style="font-size:14px;font-family:Tahoma; text-decoration: none;" href="http://playarena.pl/umbrella?city_id=139#leagueSeasonTable_14948"><span style="font-size:14px;font-family:Tahoma;color:#ea0404">Tabela 1 ligi Nike Playarena Bytom 2016/17</span></a><br /><div style="background: #fff;padding:10px;font-size:14px;font-family:Tahoma;"><p><span style="font-size:14px;">Komplet naszych spotkań w rozgrywkach 1 ligi Nike Playarena Bytom - sezon 2016/17:</span></p><br /><br /><br />
<table style="width:100%;"><tr><td>
<img style="margin-right:8px;margin-left:22px;vertical-align: middle;border:none" src="/bravia/double.png" /><span style="font-size:14px;font-family:Tahoma;">04.09 - Bravia - Extreme Team</span><span style="font-size:14px;font-family:Tahoma;color:#ea0404"> (5:9)</span><br /><br />
<img style="margin-right:8px;margin-left:22px;vertical-align: middle;border:none" src="/bravia/double.png" /><span style="font-size:14px;font-family:Tahoma">11.09 - FC Rozbark - Bravia</span><span style="font-size:14px;font-family:Tahoma;color:#ea0404"> (10:5)</span><br /><br />
<img style="margin-right:8px;margin-left:22px;vertical-align: middle;border:none" src="/bravia/double.png" /><span style="font-size:14px;font-family:Tahoma">18.09 - Bravia - Tornado Team</span><span style="font-size:14px;font-family:Tahoma;color:#ea0404"> (12:9)</span><br /><br />
<img style="margin-right:8px;margin-left:22px;vertical-align: middle;border:none" src="/bravia/double.png" /><span style="font-size:14px;font-family:Tahoma">25.09 - Mon Equipe - Bravia</span><span style="font-size:14px;font-family:Tahoma;color:#ea0404"> (14:5)</span><br /><br />
<img style="margin-right:8px;margin-left:22px;vertical-align: middle;border:none" src="/bravia/double.png" /><span style="font-size:14px;font-family:Tahoma">02.10 - Bravia - U.K Duma Bytomia 2012</span><span style="font-size:14px;font-family:Tahoma;color:#ea0404"> (16:7)</span><br /><br />
<img style="margin-right:8px;margin-left:22px;vertical-align: middle;border:none" src="/bravia/double.png" /><span style="font-size:14px;font-family:Tahoma">09.10 - Konkubenci - Bravia</span><span style="font-size:14px;font-family:Tahoma;color:#ea0404"> (3:15)</span><br /><br />
<img style="margin-right:8px;margin-left:22px;vertical-align: middle;border:none" src="/bravia/double.png" /><span style="font-size:14px;font-family:Tahoma">16.10 - Wolny termin</span><br /><br />
<img style="margin-right:8px;margin-left:22px;vertical-align: middle;border:none" src="/bravia/double.png" /><span style="font-size:14px;font-family:Tahoma">23.10 - Bravia - Rasta</span><span style="font-size:14px;font-family:Tahoma;color:#ea0404"> (23:4)</span><br /><br />
<img style="margin-right:8px;margin-left:22px;vertical-align: middle;border:none" src="/bravia/double.png" /><span style="font-size:14px;font-family:Tahoma">30.10 - Beuthen 09 - Bravia</span><span style="font-size:14px;font-family:Tahoma;color:#ea0404"> (5:5)</span><br /><br />
<img style="margin-right:8px;margin-left:22px;vertical-align: middle;border:none" src="/bravia/double.png" /><span style="font-size:14px;font-family:Tahoma">06.11 - Bravia - Celebryci</span><span style="font-size:14px;font-family:Tahoma;color:#ea0404"> (17:2)</span><br /><br />
<img style="margin-right:8px;margin-left:22px;vertical-align: middle;border:none" src="/bravia/double.png" /><span style="font-size:14px;font-family:Tahoma">13.11 - Valkiria - Bravia</span><span style="font-size:14px;font-family:Tahoma;color:#ea0404"> (8:15)</span><br /><br />
<img style="margin-right:8px;margin-left:22px;vertical-align: middle;border:none" src="/bravia/double.png" /><span style="font-size:14px;font-family:Tahoma">20.11 - Bravia - AKS Spółka</span><span style="font-size:14px;font-family:Tahoma;color:#ea0404"> (23:7)</span><br /><br />
<img style="margin-right:8px;margin-left:22px;vertical-align: middle;border:none" src="/bravia/double.png" /><span style="font-size:14px;font-family:Tahoma">27.11 - Miazga Łagiewniki - Bravia</span><span style="font-size:14px;font-family:Tahoma;color:#ea0404"> (5:24)</span><br /><br />
<img style="margin-right:8px;margin-left:22px;vertical-align: middle;border:none" src="/bravia/double.png" /><span style="font-size:14px;font-family:Tahoma">04.12 - Bravia - Trawczynczyn Team</span><span style="font-size:14px;font-family:Tahoma;color:#ea0404"> (5:9)</span><br /><br />
<img style="margin-right:8px;margin-left:22px;vertical-align: middle;border:none" src="/bravia/double.png" /><span style="font-size:14px;font-family:Tahoma;vertical-align: middle;">11.12 - Beer Team - Bravia</span><span style="font-size:14px;font-family:Tahoma;color:#ea0404"> (8:12)</span><br /><br />
</td><td style="width:20px"></td>
<td><img style="margin-right:8px;margin-left:14px;vertical-align: middle;border:none" src="/bravia/double.png" /><span style="font-size:14px;font-family:Tahoma;">05.03 - Extreme Team - Bravia</span><span style="font-size:14px;font-family:Tahoma;color:#ea0404"> (12:2)</span><br /><br />
<img style="margin-right:8px;margin-left:14px;vertical-align: middle;border:none" src="/bravia/double.png" /><span style="font-size:14px;font-family:Tahoma">12.03 - Bravia - FC Rozbark</span><span style="font-size:14px;font-family:Tahoma;color:#ea0404"> (7:14)</span><br /><br />
<img style="margin-right:8px;margin-left:14px;vertical-align: middle;border:none" src="/bravia/double.png" /><span style="font-size:14px;font-family:Tahoma">19.03 - Tornado Team - Bravia</span><span style="font-size:14px;font-family:Tahoma;color:#ea0404"> (13:16)</span><br /><br />
<img style="margin-right:8px;margin-left:14px;vertical-align: middle;border:none" src="/bravia/double.png" /><span style="font-size:14px;font-family:Tahoma">26.03 - Bravia - Mon Equipe</span><span style="font-size:14px;font-family:Tahoma;color:#ea0404"> (9:7)</span><br /><br />
<img style="margin-right:8px;margin-left:14px;vertical-align: middle;border:none" src="/bravia/double.png" /><span style="font-size:14px;font-family:Tahoma">02.04 - U.K Duma Bytomia 2012 - Bravia</span><span style="font-size:14px;font-family:Tahoma;color:#ea0404"> (6:12)</span><br /><br />
<img style="margin-right:8px;margin-left:14px;vertical-align: middle;border:none" src="/bravia/double.png" /><span style="font-size:14px;font-family:Tahoma">09.04 - Bravia - Konkubenci</span><span style="font-size:14px;font-family:Tahoma;color:#ea0404"> (13:4)</span><br /><br />
<img style="margin-right:8px;margin-left:14px;vertical-align: middle;border:none" src="/bravia/double1.png" /><span style="font-size:14px;font-family:Tahoma">16.04 - Wolny termin</span><br /><br />
<img style="margin-right:8px;margin-left:14px;vertical-align: middle;border:none" src="/bravia/double1.png" /><span style="font-size:14px;font-family:Tahoma">23.04 - Rasta - Bravia</span><span style="font-size:14px;font-family:Tahoma;color:#ea0404"> (-:-)</span><br /><br />
<img style="margin-right:8px;margin-left:14px;vertical-align: middle;border:none" src="/bravia/double1.png" /><span style="font-size:14px;font-family:Tahoma">30.04 - Bravia - Beuthen 09</span><span style="font-size:14px;font-family:Tahoma;color:#ea0404"> (-:-)</span><br /><br />
<img style="margin-right:8px;margin-left:14px;vertical-align: middle;border:none" src="/bravia/double1.png" /><span style="font-size:14px;font-family:Tahoma">07.05 - Celebryci - Bravia</span><span style="font-size:14px;font-family:Tahoma;color:#ea0404"> (-:-)</span><br /><br />
<img style="margin-right:8px;margin-left:14px;vertical-align: middle;border:none" src="/bravia/double1.png" /><span style="font-size:14px;font-family:Tahoma">14.05 - Bravia - Valkiria</span><span style="font-size:14px;font-family:Tahoma;color:#ea0404"> (-:-)</span><br /><br />
<img style="margin-right:8px;margin-left:14px;vertical-align: middle;border:none" src="/bravia/double1.png" /><span style="font-size:14px;font-family:Tahoma">21.05 - AKS Spółka - Bravia</span><span style="font-size:14px;font-family:Tahoma;color:#ea0404"> (-:-)</span><br /><br />
<img style="margin-right:8px;margin-left:14px;vertical-align: middle;border:none" src="/bravia/double1.png" /><span style="font-size:14px;font-family:Tahoma">28.05 - Bravia - Miazga Łagiewniki</span><span style="font-size:14px;font-family:Tahoma;color:#ea0404"> (-:-)</span><br /><br />
<img style="margin-right:8px;margin-left:14px;vertical-align: middle;border:none" src="/bravia/double1.png" /><span style="font-size:14px;font-family:Tahoma">04.06 - Trawczynczyn Team - Bravia</span><span style="font-size:14px;font-family:Tahoma;color:#ea0404"> (-:-)</span><br /><br />
<img style="margin-right:8px;margin-left:14px;vertical-align: middle;border:none" src="/bravia/double1.png" /><span style="font-size:14px;font-family:Tahoma;vertical-align: middle;">11.06 - Bravia - Beer Team</span><span style="font-size:14px;font-family:Tahoma;color:#ea0404"> (-:-)</span><br /><br /></td></tr></table><br /><br /></div></div>
